### PR TITLE
escape: remove too agressive JSON escaping

### LINKED ISSUE #235: Presence of double quotes in benchmark name produces broken HTML report
Similarly to #202 and #204, calling `bench` with a string containing double quotes leads to a HTML report that produces a JavaScript error in the browser console. Tested with criterion 1.5.9.0.

For example, generating a HTML report with this variant of the code from #202 illustrates the issue:
```hs
module Main where

import Criterion
import Criterion.Main

main :: IO ()
main = defaultMain
    [ env (return ()) $
       \ ~() -> bgroup "\"oops\"" [bench "dummy" $ nf id ()]
    ]
```

### PR DESCRIPTION
**Pull request by considerate**
This PR removes the overzealous "for good measure" escape of the JSON data that caused issues when using quotes in the benchmark names.

Closes #235

### CODE REVIEW

File: examples/Quotes.hs [hunk 1]
```diff
@@ -0,0 +1,10 @@
+module Main where
+
+import Criterion
+import Criterion.Main
+
+main :: IO ()
+main = defaultMain
+    [ env (return ()) $
+       \ ~() -> bgroup "\"oops\"" [bench "dummy" $ nf id ()]
```
Comment (RyanGlScott) [inline examples/Quotes.hs:9]: Can you also add a benchmark that uses single quotes instead of double quotes? That way, we can test both #202 and #235 simultaneously.

File: examples/criterion-examples.cabal [hunk 2]
```diff
@@ -112,6 +112,17 @@ executable extensible-cli
...
     optparse-applicative
 
+executable quotes
+  main-is: Quotes.hs
+
+  default-language: Haskell2010
+  ghc-options: -Wall -rtsopts
+  build-depends:
+    base == 4.*,
+    base-compat-batteries,
```
Comment (RyanGlScott) [inline examples/criterion-examples.cabal:122]: This dependency isn't being used, so remove it.

File: examples/criterion-examples.cabal [hunk 3]
```diff
@@ -112,6 +112,17 @@ executable extensible-cli
...
+    criterion,
+    optparse-applicative
```
Comment (RyanGlScott) [inline examples/criterion-examples.cabal:124]: This dependency isn't being used either. Remove it.

File: Criterion/Report.hs [hunk 4]
```diff
@@ -129,11 +129,6 @@ escapeJSON '\x2029' = "\\u2029" -- paragraph separator
 escapeJSON '&'      = "\\u0026" -- avoid HTML entities
 escapeJSON '+'      = "\\u002b" -- + can be used in UTF-7 escape sequences
 escapeJSON '\0'     = "\\u0000" -- make null characters explicit
-escapeJSON '\n'     = "\\u000a" -- for good measure also escape newlines
```
Comment (RyanGlScott) [inline Criterion/Report.hs:132]: The Haddocks for `escapeJSON` above mention that `\n`, `\\` and friends are escaped, which is no longer true. Please update the Haddocks, and perhaps mention why `\\` _isn't_ escaped.

**Review by RyanGlScott — COMMENTED** [review]
Thanks so much, @considerate!

File: examples/Quotes.hs (hunk 1 above)
Comment (considerate) [reply examples/Quotes.hs:9]: Thank you for the suggest, I have now added a similar benchmark that uses single quotes and tested that the generated JSON and HTML looks correct.

**Review by RyanGlScott — APPROVED** [review]
Thanks!
